window.__resources = {
  "img_scene_stillness": "assets/images/img_scene_stillness.jpeg",
  "img_scene_horizon": "assets/images/img_scene_horizon.jpeg",
  "img_scene_abundance": "assets/images/img_scene_abundance.jpeg",
  "img_scene_veil": "assets/images/img_scene_veil.jpeg",
  "img_neutral_wall": "assets/images/img_neutral_wall.jpeg",
  "img_scene_duality": "assets/images/img_scene_duality.jpeg",
  "img_scene_sunbeam": "assets/images/img_scene_sunbeam.jpeg",
  "img_scene_restraint": "assets/images/img_scene_restraint.jpeg",
  "img_scene_time": "assets/images/img_scene_time.jpeg",
  "img_neutral_light": "assets/images/img_neutral_light.jpeg",
  "img_scene_anchor": "assets/images/img_scene_anchor.jpeg",
  "img_scene_glow": "assets/images/img_scene_glow.jpeg",
  "img_neutral_dust": "assets/images/img_neutral_dust.jpeg",
  "img_scene_clay": "assets/images/img_scene_clay.jpeg",
  "img_scene_drape_dark": "assets/images/img_scene_drape_dark.jpeg",
  "img_scene_dusk": "assets/images/img_scene_dusk.jpeg",
  "img_p01_0": "assets/images/img_p01_0.jpeg",
};
